// services/pdfPuppeteer.service.js
const puppeteer = require('puppeteer');

class PDFPuppeteerService {
    /**
     * Generate PDF from HTML content using Puppeteer
     */
    async generateDocumentPDF(document, user) {
        try {
            // Launch a headless browser
            const browser = await puppeteer.launch({
                headless: 'new',
                args: ['--no-sandbox', '--disable-setuid-sandbox']
            });
            
            const page = await browser.newPage();
            
            // Create HTML content with proper styling
            const htmlContent = this.generateHTML(document, user);
            
            // Set the HTML content
            await page.setContent(htmlContent, {
                waitUntil: 'networkidle0'
            });
            
            // Generate PDF
            const pdfBuffer = await page.pdf({
                format: 'A4',
                margin: {
                    top: '50px',
                    bottom: '50px',
                    left: '50px',
                    right: '50px'
                },
                printBackground: true,
                displayHeaderFooter: true,
                headerTemplate: '<div></div>',
                footerTemplate: `
                    <div style="width: 100%; font-size: 8px; color: #999; text-align: center; padding-bottom: 10px;">
                        <span>Page <span class="pageNumber"></span> of <span class="totalPages"></span></span>
                        <span style="float: right; margin-right: 50px;">Generated by GameForge</span>
                    </div>
                `
            });
            
            await browser.close();
            return pdfBuffer;
            
        } catch (error) {
            console.error("Puppeteer PDF generation error:", error);
            throw error;
        }
    }

    /**
     * Generate styled HTML from document data
     */
    generateHTML(document, user) {
        return `
        <!DOCTYPE html>
        <html>
        <head>
            <meta charset="UTF-8">
            <title>${document.title}</title>
            <style>
                body {
                    font-family: 'Helvetica', Arial, sans-serif;
                    line-height: 1.6;
                    color: #333;
                    max-width: 800px;
                    margin: 0 auto;
                    padding: 20px;
                }
                h1 {
                    font-size: 28px;
                    color: #000;
                    text-align: center;
                    margin-bottom: 5px;
                    font-weight: bold;
                }
                .document-type {
                    text-align: center;
                    color: #666;
                    font-size: 14px;
                    margin-bottom: 30px;
                }
                .divider {
                    border-bottom: 1px solid #ddd;
                    margin: 20px 0;
                }
                .metadata {
                    display: flex;
                    justify-content: space-between;
                    background: #f9f9f9;
                    padding: 15px;
                    border-radius: 5px;
                    margin-bottom: 30px;
                    font-size: 12px;
                }
                .metadata-left, .metadata-right {
                    flex: 1;
                }
                .metadata-item {
                    margin-bottom: 5px;
                }
                .metadata-label {
                    font-weight: bold;
                    color: #666;
                }
                h2 {
                    font-size: 22px;
                    color: #000;
                    margin-top: 25px;
                    margin-bottom: 15px;
                    font-weight: bold;
                }
                h3 {
                    font-size: 18px;
                    color: #333;
                    margin-top: 20px;
                    margin-bottom: 10px;
                    font-weight: bold;
                }
                p {
                    margin-bottom: 15px;
                    text-align: left;
                }
                ul, ol {
                    margin-bottom: 15px;
                    padding-left: 30px;
                }
                li {
                    margin-bottom: 5px;
                }
                .ai-badge {
                    display: inline-block;
                    background: #f3e8ff;
                    color: #6b21a8;
                    padding: 2px 8px;
                    border-radius: 12px;
                    font-size: 11px;
                    font-weight: normal;
                    margin-left: 10px;
                }
                .version-badge {
                    display: inline-block;
                    background: #e5e5e5;
                    color: #333;
                    padding: 2px 8px;
                    border-radius: 12px;
                    font-size: 11px;
                    margin-left: 10px;
                }
                .footer {
                    margin-top: 50px;
                    text-align: center;
                    color: #999;
                    font-size: 10px;
                }
            </style>
        </head>
        <body>
            <h1>${document.title}</h1>
            <div class="document-type">
                ${document.type}
                ${document.generatedByAI ? '<span class="ai-badge">AI Generated</span>' : ''}
                <span class="version-badge">v${document.currentVersion || 1}</span>
            </div>
            
            <div class="divider"></div>
            
            <div class="metadata">
                <div class="metadata-left">
                    <div class="metadata-item">
                        <span class="metadata-label">Created:</span> 
                        ${new Date(document.createdAt).toLocaleDateString()}
                    </div>
                    <div class="metadata-item">
                        <span class="metadata-label">Last Updated:</span> 
                        ${new Date(document.updatedAt).toLocaleDateString()}
                    </div>
                    <div class="metadata-item">
                        <span class="metadata-label">Created by:</span> 
                        ${user?.username || 'Unknown'}
                    </div>
                </div>
                <div class="metadata-right">
                    <div class="metadata-item">
                        <span class="metadata-label">Word Count:</span> 
                        ${document.wordCount}
                    </div>
                    <div class="metadata-item">
                        <span class="metadata-label">Reading Time:</span> 
                        ${document.readingTime} min
                    </div>
                </div>
            </div>
            
            <div class="content">
                ${document.content || '<p>No content</p>'}
            </div>
            
            <div class="footer">
                Generated by GameForge on ${new Date().toLocaleDateString()}
            </div>
        </body>
        </html>
        `;
    }
}

module.exports = new PDFPuppeteerService();